/**
 * Error code and severity enumerations
 */

/**
 * Categorized error codes for the application.
 * Prefixes indicate the error category:
 * - VALIDATION_* : Input validation errors
 * - DATABASE_* : Database operation errors
 * - EXTERNAL_SERVICE_* : External service errors
 * - QUEUE_* : Message queue errors
 * - CONFIGURATION_* : Configuration errors
 * - SECURITY_* : Security, authentication, and privacy errors
 * - INTERNAL_* : Internal/programming errors
 */
export enum ErrorCode {
  // Validation Errors (1xxx)
  VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT',
  VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
  VALIDATION_OUT_OF_RANGE = 'VALIDATION_OUT_OF_RANGE',
  VALIDATION_CONSTRAINT_VIOLATION = 'VALIDATION_CONSTRAINT_VIOLATION',
  VALIDATION_TYPE_MISMATCH = 'VALIDATION_TYPE_MISMATCH',
  VALIDATION_INVALID_STATE = 'VALIDATION_INVALID_STATE',

  // Database Errors (2xxx)
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR',
  DATABASE_CONSTRAINT_VIOLATION = 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_NOT_FOUND = 'DATABASE_NOT_FOUND',
  DATABASE_DUPLICATE_ENTRY = 'DATABASE_DUPLICATE_ENTRY',
  DATABASE_TRANSACTION_ERROR = 'DATABASE_TRANSACTION_ERROR',
  DATABASE_TIMEOUT = 'DATABASE_TIMEOUT',
  DATABASE_MIGRATION_ERROR = 'DATABASE_MIGRATION_ERROR',

  // External Service Errors (3xxx)
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_RATE_LIMITED = 'EXTERNAL_SERVICE_RATE_LIMITED',
  EXTERNAL_SERVICE_AUTH_ERROR = 'EXTERNAL_SERVICE_AUTH_ERROR',
  EXTERNAL_SERVICE_INVALID_RESPONSE = 'EXTERNAL_SERVICE_INVALID_RESPONSE',

  // Telegram-specific errors
  TELEGRAM_CONNECTION_ERROR = 'TELEGRAM_CONNECTION_ERROR',
  TELEGRAM_AUTH_ERROR = 'TELEGRAM_AUTH_ERROR',
  TELEGRAM_API_ERROR = 'TELEGRAM_API_ERROR',
  TELEGRAM_RATE_LIMITED = 'TELEGRAM_RATE_LIMITED',
  TELEGRAM_FLOOD_WAIT = 'TELEGRAM_FLOOD_WAIT',
  TELEGRAM_SESSION_EXPIRED = 'TELEGRAM_SESSION_EXPIRED',
  TELEGRAM_CHAT_NOT_FOUND = 'TELEGRAM_CHAT_NOT_FOUND',
  TELEGRAM_MESSAGE_NOT_FOUND = 'TELEGRAM_MESSAGE_NOT_FOUND',
  TELEGRAM_MEDIA_DOWNLOAD_ERROR = 'TELEGRAM_MEDIA_DOWNLOAD_ERROR',

  // LLM-specific errors
  LLM_CONNECTION_ERROR = 'LLM_CONNECTION_ERROR',
  LLM_API_ERROR = 'LLM_API_ERROR',
  LLM_RATE_LIMITED = 'LLM_RATE_LIMITED',
  LLM_TIMEOUT = 'LLM_TIMEOUT',
  LLM_INVALID_RESPONSE = 'LLM_INVALID_RESPONSE',
  LLM_MODEL_NOT_FOUND = 'LLM_MODEL_NOT_FOUND',
  LLM_CONTEXT_LENGTH_EXCEEDED = 'LLM_CONTEXT_LENGTH_EXCEEDED',
  LLM_CONTENT_FILTERED = 'LLM_CONTENT_FILTERED',

  // Intent Classification-specific errors
  INTENT_CLASSIFICATION_TIMEOUT = 'INTENT_CLASSIFICATION_TIMEOUT',
  INTENT_CLASSIFICATION_FAILED = 'INTENT_CLASSIFICATION_FAILED',

  // Embedding-specific errors
  EMBEDDING_CONNECTION_ERROR = 'EMBEDDING_CONNECTION_ERROR',
  EMBEDDING_API_ERROR = 'EMBEDDING_API_ERROR',
  EMBEDDING_RATE_LIMITED = 'EMBEDDING_RATE_LIMITED',
  EMBEDDING_TIMEOUT = 'EMBEDDING_TIMEOUT',
  EMBEDDING_INVALID_INPUT = 'EMBEDDING_INVALID_INPUT',
  EMBEDDING_MODEL_NOT_FOUND = 'EMBEDDING_MODEL_NOT_FOUND',
  EMBEDDING_DIMENSION_MISMATCH = 'EMBEDDING_DIMENSION_MISMATCH',

  // Queue Errors (4xxx)
  QUEUE_RETRY_EXHAUSTED = 'QUEUE_RETRY_EXHAUSTED',
  QUEUE_CIRCUIT_OPEN = 'QUEUE_CIRCUIT_OPEN',
  QUEUE_PROCESSING_ERROR = 'QUEUE_PROCESSING_ERROR',
  QUEUE_ENQUEUE_ERROR = 'QUEUE_ENQUEUE_ERROR',
  QUEUE_DEQUEUE_ERROR = 'QUEUE_DEQUEUE_ERROR',
  QUEUE_ITEM_NOT_FOUND = 'QUEUE_ITEM_NOT_FOUND',
  QUEUE_DEAD_LETTER = 'QUEUE_DEAD_LETTER',
  QUEUE_TIMEOUT = 'QUEUE_TIMEOUT',

  // Configuration Errors (5xxx)
  CONFIGURATION_MISSING = 'CONFIGURATION_MISSING',
  CONFIGURATION_INVALID = 'CONFIGURATION_INVALID',
  CONFIGURATION_TYPE_ERROR = 'CONFIGURATION_TYPE_ERROR',
  CONFIGURATION_VALIDATION_ERROR = 'CONFIGURATION_VALIDATION_ERROR',
  CONFIGURATION_SCHEMA_ERROR = 'CONFIGURATION_SCHEMA_ERROR',
  CONFIGURATION_ENVIRONMENT_ERROR = 'CONFIGURATION_ENVIRONMENT_ERROR',

  // Security Errors (6xxx)
  SECURITY_AUTH_FAILED = 'SECURITY_AUTH_FAILED',
  SECURITY_VALIDATION_FAILED = 'SECURITY_VALIDATION_FAILED',
  SECURITY_RATE_LIMITED = 'SECURITY_RATE_LIMITED',
  SECURITY_UNAUTHORIZED = 'SECURITY_UNAUTHORIZED',
  SECURITY_FORBIDDEN = 'SECURITY_FORBIDDEN',
  SECURITY_ENCRYPTION_FAILED = 'SECURITY_ENCRYPTION_FAILED',
  SECURITY_DECRYPTION_FAILED = 'SECURITY_DECRYPTION_FAILED',
  SECURITY_KEY_DERIVATION_FAILED = 'SECURITY_KEY_DERIVATION_FAILED',
  SECURITY_PII_DETECTED = 'SECURITY_PII_DETECTED',
  SECURITY_POLICY_VIOLATION = 'SECURITY_POLICY_VIOLATION',
  SECURITY_DATA_EXPORT_FAILED = 'SECURITY_DATA_EXPORT_FAILED',
  SECURITY_DATA_DELETION_FAILED = 'SECURITY_DATA_DELETION_FAILED',

  // Contact-specific errors
  CONTACT_PHONE_INVALID = 'CONTACT_PHONE_INVALID',
  CONTACT_NOT_FOUND = 'CONTACT_NOT_FOUND',
  CONTACT_ALREADY_EXISTS = 'CONTACT_ALREADY_EXISTS',
  CONTACT_DATABASE_ERROR = 'CONTACT_DATABASE_ERROR',
  CONTACT_INVALID_NAME = 'CONTACT_INVALID_NAME',

  // Identity-specific errors
  IDENTITY_USER_NOT_FOUND = 'IDENTITY_USER_NOT_FOUND',
  IDENTITY_CONVERSATION_NOT_FOUND = 'IDENTITY_CONVERSATION_NOT_FOUND',
  IDENTITY_DUPLICATE_PLATFORM_USER = 'IDENTITY_DUPLICATE_PLATFORM_USER',
  IDENTITY_DATABASE_ERROR = 'IDENTITY_DATABASE_ERROR',

  // Internal Errors (9xxx)
  INTERNAL_UNEXPECTED = 'INTERNAL_UNEXPECTED',
  INTERNAL_INVARIANT_VIOLATION = 'INTERNAL_INVARIANT_VIOLATION',
  INTERNAL_NOT_IMPLEMENTED = 'INTERNAL_NOT_IMPLEMENTED',
  INTERNAL_ASSERTION_FAILED = 'INTERNAL_ASSERTION_FAILED',
  INTERNAL_STATE_CORRUPTION = 'INTERNAL_STATE_CORRUPTION',
}

/**
 * Error severity levels for logging and alerting.
 *
 * - CRITICAL: System is unusable, immediate attention required
 * - HIGH: Major functionality impaired, urgent attention needed
 * - MEDIUM: Partial functionality loss, should be addressed soon
 * - LOW: Minor issue, can be addressed during normal operations
 */
export enum ErrorSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

/**
 * Get the appropriate error severity based on error code
 */
export function getSeverityForCode(code: ErrorCode): ErrorSeverity {
  // Critical errors
  if (
    code === ErrorCode.DATABASE_CONNECTION_ERROR ||
    code === ErrorCode.CONFIGURATION_MISSING ||
    code === ErrorCode.CONFIGURATION_INVALID ||
    code === ErrorCode.INTERNAL_INVARIANT_VIOLATION ||
    code === ErrorCode.INTERNAL_STATE_CORRUPTION ||
    code === ErrorCode.INTERNAL_UNEXPECTED ||
    code === ErrorCode.SECURITY_ENCRYPTION_FAILED ||
    code === ErrorCode.SECURITY_KEY_DERIVATION_FAILED
  ) {
    return ErrorSeverity.CRITICAL;
  }

  // High severity errors
  if (
    code.startsWith('DATABASE_') ||
    code.startsWith('EXTERNAL_SERVICE_') ||
    code.startsWith('TELEGRAM_') ||
    code.startsWith('LLM_') ||
    code.startsWith('EMBEDDING_') ||
    code.startsWith('SECURITY_') ||
    code === ErrorCode.QUEUE_RETRY_EXHAUSTED ||
    code === ErrorCode.QUEUE_CIRCUIT_OPEN
  ) {
    return ErrorSeverity.HIGH;
  }

  // Medium severity errors
  if (
    code.startsWith('QUEUE_') ||
    code.startsWith('IDENTITY_') ||
    code === ErrorCode.VALIDATION_INVALID_STATE
  ) {
    return ErrorSeverity.MEDIUM;
  }

  // Low severity errors (validation)
  return ErrorSeverity.LOW;
}
