import { randomUUID } from 'crypto';
import { DAVClient } from 'tsdav';
import type { DAVCalendar } from 'tsdav';
import ICAL from 'ical.js';
import { logger } from '../utils/logger';
import { ExternalServiceError } from '../errors/error-classes.js';

/** External service name used in error reporting. */
const CALDAV_SERVICE = 'caldav';

/** Product identifier written into generated iCalendar objects. */
const ICS_PRODID = '-//jarvis//calendar//EN';

/** iCalendar spec version. */
const ICS_VERSION = '2.0';

/**
 * A normalized calendar event as exposed to the rest of the application.
 * Times are ISO-8601 strings (UTC).
 */
export interface CalendarEvent {
  uid: string;
  title: string;
  startISO: string;
  endISO: string;
  location?: string;
  notes?: string;
}

/**
 * Input shape for creating a new event. `uid` is generated by the client if omitted.
 */
export interface NewCalendarEvent {
  title: string;
  startISO: string;
  endISO: string;
  location?: string;
  notes?: string;
}

export interface CalendarClientConfig {
  serverUrl: string;
  appleId: string;
  appPassword: string;
  /** Target calendar display name. Empty string means "use the first calendar". */
  calendarName: string;
}

/**
 * CalendarClient
 *
 * Thin wrapper around a CalDAV server (iCloud) using `tsdav` for transport and
 * `ical.js` for parsing/building iCalendar (VEVENT) objects.
 *
 * Responsibilities:
 * - Lazily log in and discover the target calendar (cached after first use)
 * - Read events within a time range
 * - Create new events (confirm-first gating lives in CalendarService, not here)
 */
export class CalendarClient {
  private readonly config: CalendarClientConfig;
  private client: DAVClient | null = null;
  private targetCalendar: DAVCalendar | null = null;

  constructor(config: CalendarClientConfig) {
    this.config = config;
  }

  /**
   * Ensure we are logged in and have resolved the target calendar.
   * Safe to call repeatedly; work is done only once.
   */
  private async ensureConnected(): Promise<DAVCalendar> {
    if (this.targetCalendar) {
      return this.targetCalendar;
    }

    if (!this.config.appleId || !this.config.appPassword) {
      throw new ExternalServiceError(
        CALDAV_SERVICE,
        'Calendar credentials are not configured (CALENDAR_APPLE_ID / CALENDAR_APP_PASSWORD).'
      );
    }

    try {
      this.client = new DAVClient({
        serverUrl: this.config.serverUrl,
        credentials: {
          username: this.config.appleId,
          password: this.config.appPassword,
        },
        authMethod: 'Basic',
        defaultAccountType: 'caldav',
      });

      await this.client.login();

      const calendars = await this.client.fetchCalendars();
      if (!calendars || calendars.length === 0) {
        throw new ExternalServiceError(
          CALDAV_SERVICE,
          'No calendars found for the configured account.'
        );
      }

      const target = this.selectCalendar(calendars);
      this.targetCalendar = target;

      logger.info('[CalendarClient] Connected to CalDAV', {
        calendarCount: calendars.length,
        target: this.displayName(target),
      });

      return target;
    } catch (error) {
      // Reset so a later call can retry a fresh login.
      this.client = null;
      this.targetCalendar = null;

      if (error instanceof ExternalServiceError) {
        throw error;
      }

      const message = error instanceof Error ? error.message : 'Unknown error';
      throw new ExternalServiceError(CALDAV_SERVICE, `Failed to connect to calendar: ${message}`, {
        cause: error instanceof Error ? error : undefined,
      });
    }
  }

  /**
   * Choose the target calendar. Prefers an exact (case-insensitive) display-name
   * match when `calendarName` is configured; otherwise falls back to the first
   * calendar the account exposes.
   */
  private selectCalendar(calendars: DAVCalendar[]): DAVCalendar {
    const wanted = this.config.calendarName.trim().toLowerCase();
    if (wanted) {
      const match = calendars.find((c) => this.displayName(c).toLowerCase() === wanted);
      if (match) {
        return match;
      }
      logger.warn('[CalendarClient] Configured calendar not found, using first calendar', {
        wanted: this.config.calendarName,
        available: calendars.map((c) => this.displayName(c)),
      });
    }
    return calendars[0];
  }

  /** Extract a human-readable display name from a DAVCalendar. */
  private displayName(calendar: DAVCalendar): string {
    const name = calendar.displayName;
    return typeof name === 'string' ? name : '';
  }

  /**
   * List events overlapping the given time range.
   *
   * @param startISO - inclusive range start (ISO-8601)
   * @param endISO - exclusive range end (ISO-8601)
   */
  async listEvents(startISO: string, endISO: string): Promise<CalendarEvent[]> {
    const calendar = await this.ensureConnected();

    try {
      const objects = await this.client!.fetchCalendarObjects({
        calendar,
        timeRange: { start: startISO, end: endISO },
      });

      const events: CalendarEvent[] = [];
      for (const object of objects) {
        if (!object.data) {
          continue;
        }
        events.push(...this.parseEvents(object.data));
      }

      events.sort((a, b) => a.startISO.localeCompare(b.startISO));
      return events;
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      throw new ExternalServiceError(CALDAV_SERVICE, `Failed to read calendar events: ${message}`, {
        cause: error instanceof Error ? error : undefined,
      });
    }
  }

  /**
   * Create a new event on the target calendar.
   * @returns the UID assigned to the created event.
   */
  async createEvent(event: NewCalendarEvent): Promise<string> {
    const calendar = await this.ensureConnected();
    const uid = randomUUID();
    const iCalString = this.buildICS({ ...event, uid });

    try {
      const response = await this.client!.createCalendarObject({
        calendar,
        filename: `${uid}.ics`,
        iCalString,
      });

      if (!response.ok) {
        throw new Error(`CalDAV responded ${response.status} ${response.statusText}`);
      }

      logger.info('[CalendarClient] Event created', { uid, title: event.title });
      return uid;
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      throw new ExternalServiceError(CALDAV_SERVICE, `Failed to create calendar event: ${message}`, {
        cause: error instanceof Error ? error : undefined,
      });
    }
  }

  /** Parse a VCALENDAR string into normalized events (all VEVENTs it contains). */
  private parseEvents(data: string): CalendarEvent[] {
    const jcal = ICAL.parse(data);
    const comp = new ICAL.Component(jcal);
    const vevents = comp.getAllSubcomponents('vevent');

    return vevents.map((ve) => {
      const event = new ICAL.Event(ve);
      return {
        uid: event.uid || '',
        title: event.summary || '(untitled)',
        startISO: event.startDate.toJSDate().toISOString(),
        endISO: event.endDate.toJSDate().toISOString(),
        location: event.location || undefined,
        notes: event.description || undefined,
      };
    });
  }

  /** Build a minimal VCALENDAR/VEVENT string in UTC for the given event. */
  private buildICS(event: NewCalendarEvent & { uid: string }): string {
    const calendar = new ICAL.Component(['vcalendar', [], []]);
    calendar.updatePropertyWithValue('prodid', ICS_PRODID);
    calendar.updatePropertyWithValue('version', ICS_VERSION);

    const vevent = new ICAL.Component('vevent');
    const icalEvent = new ICAL.Event(vevent);
    icalEvent.uid = event.uid;
    icalEvent.summary = event.title;
    // `true` => emit as UTC (trailing Z), which iCloud accepts unambiguously.
    icalEvent.startDate = ICAL.Time.fromJSDate(new Date(event.startISO), true);
    icalEvent.endDate = ICAL.Time.fromJSDate(new Date(event.endISO), true);
    if (event.location) {
      icalEvent.location = event.location;
    }
    if (event.notes) {
      icalEvent.description = event.notes;
    }

    calendar.addSubcomponent(vevent);
    return calendar.toString();
  }
}
