/**
 * Loop Log Parser
 *
 * Parses loop.log files generated by loop.sh script.
 * The log contains JSON streaming format with:
 * - loop_start_marker events
 * - message_start events (contain model info)
 * - message_delta events (contain token usage)
 * - Task tool invocations for subagents
 */

import { readFile } from 'fs/promises';
import { createLogger } from './logger.js';
import type { LoopLogEntry, LoopLogMetrics } from '../types/plan.types.js';

const logger = createLogger('LoopLogParser');

// Claude Opus 4.5 pricing (per 1M tokens)
const PRICING = {
  INPUT: 15, // $15/1M input tokens
  OUTPUT: 75, // $75/1M output tokens
  CACHE_READ: 1.5, // $1.50/1M cache read tokens (90% discount)
  CACHE_WRITE: 18.75, // $18.75/1M cache write tokens (25% premium)
} as const;

/**
 * Stream event type for message_start events
 */
interface MessageStartEvent {
  type: 'stream_event';
  event: {
    type: 'message_start';
    message: {
      model: string;
    };
  };
}

/**
 * Stream event type for message_delta events
 */
interface MessageDeltaEvent {
  type: 'stream_event';
  event: {
    type: 'message_delta';
    usage: {
      input_tokens: number;
      output_tokens: number;
      cache_read_input_tokens?: number;
      cache_creation_input_tokens?: number;
    };
  };
}

/**
 * Loop start marker event
 */
interface LoopStartEvent {
  type: 'loop_start_marker';
  message: string;
}

/**
 * Task tool invocation (subagent)
 */
interface TaskToolUseEvent {
  type: 'assistant';
  message: {
    content: Array<{
      type: 'tool_use';
      name: 'Task';
      id: string;
      input: {
        model?: string;
      };
    }>;
  };
}

/**
 * Task result (subagent completion)
 */
interface TaskResultEvent {
  type: 'user';
  tool_use_result: {
    agentId: string;
    totalTokens?: number;
    totalDurationMs?: number;
    totalToolUseCount?: number;
  };
  message: {
    content: Array<{
      tool_use_id: string;
    }>;
  };
}

type LogEvent =
  | MessageStartEvent
  | MessageDeltaEvent
  | LoopStartEvent
  | TaskToolUseEvent
  | TaskResultEvent
  | Record<string, unknown>;

/**
 * Calculate cost from token counts using Claude Opus 4.5 pricing
 */
function calculateCost(
  inputTokens: number,
  outputTokens: number,
  cacheReadTokens: number,
  cacheWriteTokens: number
): number {
  const inputCost = (inputTokens / 1_000_000) * PRICING.INPUT;
  const outputCost = (outputTokens / 1_000_000) * PRICING.OUTPUT;
  const cacheReadCost = (cacheReadTokens / 1_000_000) * PRICING.CACHE_READ;
  const cacheWriteCost = (cacheWriteTokens / 1_000_000) * PRICING.CACHE_WRITE;

  return inputCost + outputCost + cacheReadCost + cacheWriteCost;
}

/**
 * Parse a single log line into a structured event
 * Returns null for malformed JSON or lines that don't match expected format
 */
export function parseLoopLogLine(line: string): LogEvent | null {
  const trimmed = line.trim();
  if (!trimmed) {
    return null;
  }

  try {
    const parsed = JSON.parse(trimmed) as LogEvent;
    return parsed;
  } catch (error) {
    // Skip malformed JSON lines gracefully
    logger.debug('Skipping malformed JSON line', { error: error instanceof Error ? error.message : 'Unknown error' });
    return null;
  }
}

/**
 * Parse entire loop log content and calculate metrics
 */
export function parseLoopLog(logContent: string): LoopLogMetrics {
  const lines = logContent.split('\n');
  const entries: LoopLogEntry[] = [];

  let currentIteration = 0;
  let iterationStartTime: Date | null = null;
  let iterationTokensIn = 0;
  let iterationTokensOut = 0;
  let iterationCacheRead = 0;
  let iterationCacheWrite = 0;

  for (const line of lines) {
    const event = parseLoopLogLine(line);
    if (!event) continue;

    // Detect loop start marker
    if (
      typeof event === 'object' &&
      event !== null &&
      'type' in event &&
      event.type === 'loop_start_marker'
    ) {
      // Save previous iteration if it exists
      if (currentIteration > 0 && iterationStartTime) {
        const cost = calculateCost(
          iterationTokensIn,
          iterationTokensOut,
          iterationCacheRead,
          iterationCacheWrite
        );

        entries.push({
          iteration: currentIteration,
          timestamp: iterationStartTime,
          tokensIn: iterationTokensIn,
          tokensOut: iterationTokensOut,
          cacheRead: iterationCacheRead,
          cacheWrite: iterationCacheWrite,
          cost,
        });
      }

      // Start new iteration
      currentIteration++;
      iterationStartTime = new Date();
      iterationTokensIn = 0;
      iterationTokensOut = 0;
      iterationCacheRead = 0;
      iterationCacheWrite = 0;
      continue;
    }

    // Extract token usage from message_delta events
    if (
      typeof event === 'object' &&
      event !== null &&
      'type' in event &&
      event.type === 'stream_event' &&
      'event' in event &&
      typeof event.event === 'object' &&
      event.event !== null &&
      'type' in event.event &&
      event.event.type === 'message_delta'
    ) {
      const deltaEvent = event as MessageDeltaEvent;
      const usage = deltaEvent.event.usage;

      iterationTokensIn += usage.input_tokens || 0;
      iterationTokensOut += usage.output_tokens || 0;
      iterationCacheRead += usage.cache_read_input_tokens || 0;
      iterationCacheWrite += usage.cache_creation_input_tokens || 0;
    }
  }

  // Save final iteration if it exists
  if (currentIteration > 0 && iterationStartTime) {
    const cost = calculateCost(
      iterationTokensIn,
      iterationTokensOut,
      iterationCacheRead,
      iterationCacheWrite
    );

    entries.push({
      iteration: currentIteration,
      timestamp: iterationStartTime,
      tokensIn: iterationTokensIn,
      tokensOut: iterationTokensOut,
      cacheRead: iterationCacheRead,
      cacheWrite: iterationCacheWrite,
      cost,
    });
  }

  // Calculate totals
  const totalTokensIn = entries.reduce((sum, e) => sum + e.tokensIn, 0);
  const totalTokensOut = entries.reduce((sum, e) => sum + e.tokensOut, 0);
  const totalCacheRead = entries.reduce((sum, e) => sum + (e.cacheRead || 0), 0);
  const totalCacheWrite = entries.reduce((sum, e) => sum + (e.cacheWrite || 0), 0);
  const totalCost = entries.reduce((sum, e) => sum + e.cost, 0);

  // Calculate average duration if we have timestamps
  let averageDuration: number | undefined;
  if (entries.length > 1) {
    const durations: number[] = [];
    for (let i = 1; i < entries.length; i++) {
      const duration = entries[i].timestamp.getTime() - entries[i - 1].timestamp.getTime();
      durations.push(duration);
    }
    if (durations.length > 0) {
      averageDuration = durations.reduce((sum, d) => sum + d, 0) / durations.length;
    }
  }

  return {
    totalIterations: entries.length,
    totalTokensIn,
    totalTokensOut,
    totalCacheRead,
    totalCacheWrite,
    totalCost,
    averageDuration,
    entries,
  };
}

/**
 * Parse loop log incrementally from a file, starting from a specific line number
 * Useful for tail-like reading and real-time progress updates
 *
 * @param logPath - Path to the loop.log file
 * @param fromLine - Line number to start reading from (0-indexed)
 * @returns Metrics from the new lines and the last line number read
 */
export async function parseLoopLogIncremental(
  logPath: string,
  fromLine: number = 0
): Promise<{ metrics: LoopLogMetrics; lastLine: number }> {
  try {
    const content = await readFile(logPath, 'utf-8');
    const lines = content.split('\n');

    // Extract lines from the specified offset
    const newLines = lines.slice(fromLine);
    const newContent = newLines.join('\n');

    // Parse the new content
    const metrics = parseLoopLog(newContent);

    // Return metrics and the last line number
    const lastLine = lines.length;

    return { metrics, lastLine };
  } catch (error) {
    logger.error('Failed to parse loop log incrementally', {
      error: error instanceof Error ? error.message : 'Unknown error',
      logPath,
      fromLine,
    });

    // Return empty metrics on error
    return {
      metrics: {
        totalIterations: 0,
        totalTokensIn: 0,
        totalTokensOut: 0,
        totalCacheRead: 0,
        totalCacheWrite: 0,
        totalCost: 0,
        entries: [],
      },
      lastLine: fromLine,
    };
  }
}

/**
 * Extract subagent statistics from log content
 * Returns array of subagent info with model, tokens, duration, tool count
 */
export function extractSubagentStats(logContent: string): Array<{
  agentId: string;
  model: string;
  tokens: number;
  durationMs: number;
  toolCount: number;
}> {
  const lines = logContent.split('\n');
  const stats: Array<{
    agentId: string;
    model: string;
    tokens: number;
    durationMs: number;
    toolCount: number;
  }> = [];

  // Build map of tool_use_id -> model from Task invocations
  const modelMap = new Map<string, string>();

  for (const line of lines) {
    const event = parseLoopLogLine(line);
    if (!event) continue;

    // Track Task tool invocations with their models
    if (
      typeof event === 'object' &&
      event !== null &&
      'type' in event &&
      event.type === 'assistant' &&
      'message' in event
    ) {
      const taskEvent = event as TaskToolUseEvent;
      const content = taskEvent.message.content;

      if (Array.isArray(content)) {
        for (const item of content) {
          if (item.type === 'tool_use' && item.name === 'Task') {
            const model = item.input?.model || 'opus';
            modelMap.set(item.id, model);
          }
        }
      }
    }

    // Match tool results with their models
    if (
      typeof event === 'object' &&
      event !== null &&
      'type' in event &&
      event.type === 'user' &&
      'tool_use_result' in event &&
      typeof event.tool_use_result === 'object' &&
      event.tool_use_result !== null &&
      'agentId' in event.tool_use_result
    ) {
      const resultEvent = event as TaskResultEvent;
      const toolUseId = resultEvent.message.content[0]?.tool_use_id;
      const model = toolUseId ? modelMap.get(toolUseId) || 'opus' : 'opus';

      stats.push({
        agentId: resultEvent.tool_use_result.agentId,
        model,
        tokens: resultEvent.tool_use_result.totalTokens || 0,
        durationMs: resultEvent.tool_use_result.totalDurationMs || 0,
        toolCount: resultEvent.tool_use_result.totalToolUseCount || 0,
      });
    }
  }

  return stats;
}
